services:
  dynamodb:
    image: amazon/dynamodb-local
    command: '-jar DynamoDBLocal.jar -sharedDb'
    healthcheck:
      test: ['CMD-SHELL', 'curl -v http://dynamodb:8000']
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_REGION: ${DYNAMODB_REGION}
      AWS_ACCESS_KEY_ID: ${DYNAMODB_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${DYNAMODB_SECRET_KEY}
    depends_on:
      - dynamodb

volumes:
  dynamodb_data:
